kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-jul5-6-dsp-job-role
  annotations:
rules:
  - verbs:
      - get
      - list
      - watch
      - patch
      - update
    apiGroups:
      - v1
    resources:
      - namespace